### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by jonnor** [hansjny/OpenAlinvoice#4]
Hi. This plugin looks quite useful. However the README is missing instructions for how to install with Chrome. Can you add that, or refer to a general docs on how to install? I think it will give the project many more users.

Takk for et praktisk prosjekt!

**Comment by tiefpunkt** [comment]
@jonnor I added some instructions, are those clear enough? Or do they need some more detail?

**Comment by hansjny** [comment]
Merged installation issues. Considering this resolved!

**Comment by jonnor** [comment]
Works nicely, thank you!
